import { ComponentProps } from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';
import { colors } from './theme';
import { ConnectorPlatform } from './types';

type IonName = ComponentProps<typeof Ionicons>['name'];

export interface PlatformAction {
  id: string;
  label: string;
  hint: string;
}

export interface PlatformDef {
  id: ConnectorPlatform;
  label: string;
  short: string;
  icon: IonName;
  color: string;
  category: 'scm' | 'deploy' | 'cloud' | 'registry' | 'data' | 'remote';
  blurb: string;
  tokenLabel: string;
  tokenHint: string;
  docs: string;
  scopes: string;
  actions: PlatformAction[];
}

export const PLATFORMS: PlatformDef[] = [
  {
    id: 'github',
    label: 'GitHub',
    short: 'GH',
    icon: 'logo-github',
    color: colors.text,
    category: 'scm',
    blurb: 'Repo, issue, PR, Actions, commit file, dispatch workflow.',
    tokenLabel: 'Personal Access Token',
    tokenHint: 'ghp_… atau github_pat_…',
    docs: 'https://github.com/settings/tokens',
    scopes: 'repo · workflow · read:org · user',
    actions: [
      { id: 'whoami', label: 'Whoami', hint: 'GET /user' },
      { id: 'repos', label: 'List repos', hint: 'GET /user/repos' },
      { id: 'issues', label: 'Issues', hint: 'GET /repos/…/issues' },
      { id: 'prs', label: 'Pull requests', hint: 'GET /repos/…/pulls' },
      { id: 'actions', label: 'Actions', hint: 'GET /actions/runs' },
      { id: 'commit', label: 'Commit file', hint: 'PUT /contents' },
    ],
  },
  {
    id: 'gitlab',
    label: 'GitLab',
    short: 'GL',
    icon: 'git-branch-outline',
    color: '#fc6d26',
    category: 'scm',
    blurb: 'Projects, issues, pipelines GitLab.com / self-host.',
    tokenLabel: 'Personal Access Token',
    tokenHint: 'glpat-…',
    docs: 'https://gitlab.com/-/user_settings/personal_access_tokens',
    scopes: 'api · read_repository · write_repository',
    actions: [
      { id: 'whoami', label: 'Whoami', hint: 'GET /api/v4/user' },
      { id: 'projects', label: 'Projects', hint: 'GET /api/v4/projects' },
    ],
  },
  {
    id: 'gitea',
    label: 'Gitea / Forgejo',
    short: 'GT',
    icon: 'git-network-outline',
    color: colors.green,
    category: 'scm',
    blurb: 'Self-hosted forge. Target = base URL instance.',
    tokenLabel: 'Access token',
    tokenHint: 'token instance',
    docs: 'https://docs.gitea.com/development/api-usage',
    scopes: 'repo · write:repository',
    actions: [{ id: 'whoami', label: 'Whoami', hint: 'GET /api/v1/user' }],
  },
  {
    id: 'vercel',
    label: 'Vercel',
    short: '▲',
    icon: 'triangle-outline',
    color: colors.text,
    category: 'deploy',
    blurb: 'Projects, deployments, redeploy dari GitHub.',
    tokenLabel: 'Vercel token',
    tokenHint: 'vercel_…',
    docs: 'https://vercel.com/account/tokens',
    scopes: 'full account token',
    actions: [
      { id: 'user', label: 'User', hint: 'GET /v2/user' },
      { id: 'projects', label: 'Projects', hint: 'GET /v9/projects' },
      { id: 'deployments', label: 'Deployments', hint: 'GET /v6/deployments' },
    ],
  },
  {
    id: 'netlify',
    label: 'Netlify',
    short: 'NT',
    icon: 'leaf-outline',
    color: '#32e6e2',
    category: 'deploy',
    blurb: 'Sites & deploy hook Netlify.',
    tokenLabel: 'Personal access token',
    tokenHint: 'nf_… / nfp_…',
    docs: 'https://app.netlify.com/user/applications',
    scopes: 'sites · deploys',
    actions: [{ id: 'sites', label: 'Sites', hint: 'GET /api/v1/sites' }],
  },
  {
    id: 'cloudflare',
    label: 'Cloudflare',
    short: 'CF',
    icon: 'cloudy-outline',
    color: '#f6821f',
    category: 'deploy',
    blurb: 'Zones, Pages, Workers — token API Cloudflare.',
    tokenLabel: 'API token',
    tokenHint: 'Cloudflare API token',
    docs: 'https://dash.cloudflare.com/profile/api-tokens',
    scopes: 'Zone.Read · Pages.Write',
    actions: [
      { id: 'user', label: 'Verify', hint: 'GET /client/v4/user/tokens/verify' },
      { id: 'zones', label: 'Zones', hint: 'GET /client/v4/zones' },
    ],
  },
  {
    id: 'railway',
    label: 'Railway',
    short: 'RW',
    icon: 'train-outline',
    color: colors.violet,
    category: 'deploy',
    blurb: 'Projects Railway via GraphQL API.',
    tokenLabel: 'Account token',
    tokenHint: 'railway token',
    docs: 'https://railway.app/account/tokens',
    scopes: 'account',
    actions: [{ id: 'me', label: 'Me', hint: 'GraphQL me' }],
  },
  {
    id: 'render',
    label: 'Render',
    short: 'RD',
    icon: 'layers-outline',
    color: colors.cyan,
    category: 'deploy',
    blurb: 'Services & deploys Render.com.',
    tokenLabel: 'API key',
    tokenHint: 'rnd_…',
    docs: 'https://dashboard.render.com/u/settings#api-keys',
    scopes: 'read · deploy',
    actions: [{ id: 'services', label: 'Services', hint: 'GET /v1/services' }],
  },
  {
    id: 'flyio',
    label: 'Fly.io',
    short: 'FLY',
    icon: 'airplane-outline',
    color: colors.violet,
    category: 'deploy',
    blurb: 'Apps Fly.io (Machines API).',
    tokenLabel: 'Access token',
    tokenHint: 'fly token',
    docs: 'https://fly.io/docs/flyctl/tokens/',
    scopes: 'read · deploy',
    actions: [{ id: 'apps', label: 'Apps', hint: 'GET /graphql' }],
  },
  {
    id: 'dockerhub',
    label: 'Docker Hub',
    short: 'DH',
    icon: 'cube-outline',
    color: '#2496ed',
    category: 'registry',
    blurb: 'Repositories Docker Hub.',
    tokenLabel: 'Access token / password',
    tokenHint: 'dckr_pat_…',
    docs: 'https://hub.docker.com/settings/security',
    scopes: 'read · write',
    actions: [{ id: 'repos', label: 'Repos', hint: 'GET /v2/repositories' }],
  },
  {
    id: 'digitalocean',
    label: 'DigitalOcean',
    short: 'DO',
    icon: 'water-outline',
    color: '#0080ff',
    category: 'cloud',
    blurb: 'Account, droplets, apps — VPS MusGo.',
    tokenLabel: 'Personal access token',
    tokenHint: 'dop_v1_…',
    docs: 'https://cloud.digitalocean.com/account/api/tokens',
    scopes: 'read · write',
    actions: [
      { id: 'account', label: 'Account', hint: 'GET /v2/account' },
      { id: 'droplets', label: 'Droplets', hint: 'GET /v2/droplets' },
    ],
  },
  {
    id: 'aws',
    label: 'AWS',
    short: 'AWS',
    icon: 'cloud-outline',
    color: '#ff9900',
    category: 'cloud',
    blurb: 'Access key disimpan aman. Signing dilakukan saat native runtime.',
    tokenLabel: 'Access key + secret',
    tokenHint: 'AKIA… / secret',
    docs: 'https://console.aws.amazon.com/iam',
    scopes: 'least-privilege IAM',
    actions: [{ id: 'sts', label: 'Identity', hint: 'sts get-caller-identity' }],
  },
  {
    id: 'gcp',
    label: 'Google Cloud',
    short: 'GCP',
    icon: 'logo-google',
    color: '#4285f4',
    category: 'cloud',
    blurb: 'Service account JSON / access token.',
    tokenLabel: 'Access token',
    tokenHint: 'ya29.…',
    docs: 'https://console.cloud.google.com',
    scopes: 'cloud-platform',
    actions: [{ id: 'projects', label: 'Projects', hint: 'cloudresourcemanager' }],
  },
  {
    id: 'azure',
    label: 'Azure',
    short: 'AZ',
    icon: 'grid-outline',
    color: '#0078d4',
    category: 'cloud',
    blurb: 'Service principal / PAT Azure DevOps.',
    tokenLabel: 'Token',
    tokenHint: 'pat / client secret',
    docs: 'https://portal.azure.com',
    scopes: 'scoped SP',
    actions: [{ id: 'whoami', label: 'Profile', hint: 'ARM / devops' }],
  },
  {
    id: 'huggingface',
    label: 'Hugging Face',
    short: 'HF',
    icon: 'happy-outline',
    color: '#ffd21e',
    category: 'registry',
    blurb: 'Models, spaces, datasets — inference & hub.',
    tokenLabel: 'Access token',
    tokenHint: 'hf_…',
    docs: 'https://huggingface.co/settings/tokens',
    scopes: 'read · write',
    actions: [{ id: 'whoami', label: 'Whoami', hint: 'GET /api/whoami-v2' }],
  },
  {
    id: 'supabase',
    label: 'Supabase',
    short: 'SB',
    icon: 'server-outline',
    color: colors.green,
    category: 'data',
    blurb: 'Project URL + service role (disimpan terpisah).',
    tokenLabel: 'Service role key',
    tokenHint: 'eyJ…',
    docs: 'https://supabase.com/dashboard',
    scopes: 'service_role',
    actions: [{ id: 'health', label: 'Health', hint: 'GET /auth/v1/health' }],
  },
  {
    id: 'firebase',
    label: 'Firebase',
    short: 'FB',
    icon: 'flame-outline',
    color: '#ffca28',
    category: 'data',
    blurb: 'Web API key + project id.',
    tokenLabel: 'Web API key',
    tokenHint: 'AIza…',
    docs: 'https://console.firebase.google.com',
    scopes: 'project',
    actions: [{ id: 'meta', label: 'Project', hint: 'identitytoolkit' }],
  },
  {
    id: 'npm',
    label: 'npm',
    short: 'NPM',
    icon: 'logo-npm',
    color: '#cb3837',
    category: 'registry',
    blurb: 'Automation token untuk publish paket MusGo.',
    tokenLabel: 'Automation token',
    tokenHint: 'npm_…',
    docs: 'https://www.npmjs.com/settings/~/tokens',
    scopes: 'publish',
    actions: [{ id: 'whoami', label: 'Whoami', hint: 'GET /-/whoami' }],
  },
  {
    id: 'ssh-vps',
    label: 'SSH / VPS',
    short: 'SSH',
    icon: 'terminal-outline',
    color: colors.cyan,
    category: 'remote',
    blurb: 'Host, user, key. Bridge native / agent remote.',
    tokenLabel: 'Private key / password',
    tokenHint: '-----BEGIN … atau password',
    docs: 'ssh-keygen -t ed25519',
    scopes: 'shell',
    actions: [{ id: 'probe', label: 'Probe', hint: 'banner + recipe' }],
  },
  {
    id: 'sftp',
    label: 'SFTP',
    short: 'FTP',
    icon: 'swap-horizontal-outline',
    color: colors.mint,
    category: 'remote',
    blurb: 'Transfer file ke VPS / storage.',
    tokenLabel: 'Password / key',
    tokenHint: 'kredensial SFTP',
    docs: 'man sftp',
    scopes: 'file',
    actions: [{ id: 'ls', label: 'List', hint: 'sftp ls' }],
  },
  {
    id: 'webhook',
    label: 'Webhook',
    short: 'HOOK',
    icon: 'flash-outline',
    color: colors.amber,
    category: 'remote',
    blurb: 'Deploy hook / Slack / custom HTTPS.',
    tokenLabel: 'Optional secret',
    tokenHint: 'signing secret',
    docs: 'POST JSON',
    scopes: 'https',
    actions: [{ id: 'ping', label: 'Ping', hint: 'POST ping' }],
  },
  {
    id: 'custom',
    label: 'Custom API',
    short: 'API',
    icon: 'extension-puzzle-outline',
    color: colors.violet,
    category: 'remote',
    blurb: 'Endpoint + bearer sendiri.',
    tokenLabel: 'Bearer token',
    tokenHint: 'token',
    docs: '',
    scopes: 'custom',
    actions: [{ id: 'get', label: 'GET', hint: 'GET target' }],
  },
];

export const PLATFORM_MAP: Record<string, PlatformDef> = PLATFORMS.reduce((acc, p) => {
  acc[p.id] = p;
  return acc;
}, {} as Record<string, PlatformDef>);

export function getPlatform(id: string): PlatformDef {
  return PLATFORM_MAP[id] || PLATFORM_MAP.custom;
}

export const CATEGORY_LABEL: Record<PlatformDef['category'], string> = {
  scm: 'Source control',
  deploy: 'Deploy / CDN',
  cloud: 'Cloud / VPS',
  registry: 'Registry',
  data: 'Data / backend',
  remote: 'Remote / hook',
};
