export type ProviderDef = {
  id: string;
  name: string;
  icon: string;
  tint: string;
  tier: 'free' | 'freemium' | 'trial';
  blurb: string;
  keyHint: string;
  placeholder: string;
  envPrefix: string;
  docs: string;
  models: string[];
};

export const PROVIDERS: ProviderDef[] = [
  {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: 'router-wireless',
    tint: '#8B7CFF',
    tier: 'free',
    blurb: 'Aggregator dengan route gratis (":free" suffix) untuk puluhan model open-weight.',
    keyHint: 'sk-or-v1-…',
    placeholder: 'sk-or-v1-xxxxxxxxxxxxxxxxxxxxxxxx',
    envPrefix: 'OPENROUTER_API_KEY',
    docs: 'openrouter.ai/keys',
    models: [
      'meta-llama/llama-3.3-70b-instruct:free',
      'qwen/qwen-2.5-72b-instruct:free',
      'deepseek/deepseek-r1:free',
      'google/gemma-2-27b-it:free',
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral',
    icon: 'weather-windy',
    tint: '#FF7A18',
    tier: 'freemium',
    blurb: 'Tier gratis laplat untuk Mistral Small / Nember via API langsung.',
    keyHint: 'mistral-…',
    placeholder: 'mistral_api_key_here',
    envPrefix: 'MISTRAL_API_KEY',
    docs: 'console.mistral.ai/api-keys',
    models: ['mistral-small-latest', 'open-mistral-nemo', 'mistral-large-latest', 'codestral-latest'],
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    icon: 'google-glass',
    tint: '#4285F4',
    tier: 'free',
    blurb: 'Free tier AI Studio cukup besar untuk 1.5/2.0 Flash.',
    keyHint: 'AIza…',
    placeholder: 'AIzaSy…',
    envPrefix: 'GEMINI_API_KEY',
    docs: 'aistudio.google.com/apikey',
    models: ['gemini-2.0-flash', 'gemini-1.5-flash', 'gemini-1.5-pro', 'gemini-2.5-flash'],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    icon: 'robot',
    tint: '#10A37F',
    tier: 'trial',
    blurb: 'Kredit trial sekali pakai untuk GPT-4o mini.',
    keyHint: 'sk-proj-…',
    placeholder: 'sk-proj-xxxxxxxxxxxxxxxx',
    envPrefix: 'OPENAI_API_KEY',
    docs: 'platform.openai.com/api-keys',
    models: ['gpt-4o-mini', 'gpt-4o', 'o4-mini'],
  },
  {
    id: 'qwen',
    name: 'Qwen / DashScope',
    icon: 'message-text',
    tint: '#615CED',
    tier: 'free',
    blurb: 'Token gratis bulanan untuk Qwen 2.5 & Qwen Coder.',
    keyHint: 'sk-…',
    placeholder: 'sk-dashscope-…',
    envPrefix: 'DASHSCOPE_API_KEY',
    docs: 'bailian.console.aliyun.com',
    models: ['qwen2.5-72b-instruct', 'qwen2.5-coder-32b-instruct', 'qwen-max'],
  },
  {
    id: 'nvidia',
    name: 'NVIDIA NIM',
    icon: 'memory',
    tint: '#76B900',
    tier: 'free',
    blurb: '1.000 credit gratis untuk inference NIM endpoint.',
    keyHint: 'nvapi-…',
    placeholder: 'nvapi-xxxxx',
    envPrefix: 'NVIDIA_API_KEY',
    docs: 'build.nvidia.com/api-keys',
    models: ['nvidia/llama-3.1-405b-instruct', 'nvidia/nemotron-4-340b-instruct', 'meta/llama-3.1-70b-instruct'],
  },
  {
    id: 'requesty',
    name: 'Requesty',
    icon: 'send',
    tint: '#2E9BFF',
    tier: 'freemium',
    blurb: 'Router LLM terbuka dengan dashboard observability.',
    keyHint: 'sk-…',
    placeholder: 'sk_requesty_…',
    envPrefix: 'REQUESTY_API_KEY',
    docs: 'app.requesty.ai/keys',
    models: ['openai/gpt-4o-mini', 'google/gemini-2.0-flash-001', 'meta-llama/llama-3.3-70b-instruct'],
  },
  {
    id: 'aihubmix',
    name: 'AIHubMix',
    icon: 'tune-vertical',
    tint: '#B06BFF',
    tier: 'freemium',
    blurb: 'Satu endpoint untuk banyak vendor, model context panjang.',
    keyHint: 'sk-…',
    placeholder: 'sk-aihubmix-…',
    envPrefix: 'AIHUBMIX_API_KEY',
    docs: 'aihubmix.com/dashboard',
    models: ['aihubmix/gpt-4o-mini', 'aihubmix/claude-3.5-sonnet', 'aihubmix/gemini-2.0-flash'],
  },
  {
    id: 'opencode',
    name: 'opencode',
    icon: 'code-braces',
    tint: '#31D0AA',
    tier: 'free',
    blurb: 'Model coding gratis untuk editor lokal.',
    keyHint: 'o_v1_…',
    placeholder: 'o_v1_xxxx',
    envPrefix: 'OPENCODE_API_KEY',
    docs: 'opencode.ai/auth',
    models: ['opencode/glm-4.6', 'opencode/qwen3-coder', 'opencode/deepseek-v3.1'],
  },
  {
    id: 'zai',
    name: 'Z.ai (Zhipu)',
    icon: 'hexagon-outline',
    tint: '#F2A93B',
    tier: 'free',
    blurb: 'GLM-4.6 & CodeGeeX dengan kuota gratis harian.',
    keyHint: '…',
    placeholder: 'zhipu_api_key',
    envPrefix: 'ZAI_API_KEY',
    docs: 'open.bigmodel.cn',
    models: ['glm-4.6', 'glm-4.5-air', 'codegeex-4'],
  },
  {
    id: 'kilocode',
    name: 'Kilo Code',
    icon: 'cube-outline',
    tint: '#E85D75',
    tier: 'freemium',
    blurb: 'CLI coding agent dengan model gateway sendiri.',
    keyHint: 'kilo-…',
    placeholder: 'kilo_api_key',
    envPrefix: 'KILO_API_KEY',
    docs: 'app.kilocode.ai',
    models: ['kilo/google/gemini-2.5-flash', 'kilo/openai/gpt-4.1-mini', 'kilo/anthropic/claude-sonnet-4'],
  },
  {
    id: 'groq',
    name: 'Groq',
    icon: 'lightning-bolt',
    tint: '#F55036',
    tier: 'free',
    blurb: 'Inference sangat cepat (LPU) dengan free tier harian.',
    keyHint: 'gsk_…',
    placeholder: 'gsk_xxxxxxxx',
    envPrefix: 'GROQ_API_KEY',
    docs: 'console.groq.com/keys',
    models: ['llama-3.3-70b-versatile', 'mixtral-8x7b-32768', 'gemma2-9b-it'],
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    icon: 'emoticon-happy-outline',
    tint: '#FFD21E',
    tier: 'freemium',
    blurb: 'Inference API gratis (rate-limited) untuk ribuan model.',
    keyHint: 'hf_…',
    placeholder: 'hf_xxxxxxxxxxxx',
    envPrefix: 'HF_TOKEN',
    docs: 'huggingface.co/settings/tokens',
    models: ['meta-llama/Llama-3.3-70B-Instruct', 'Qwen/Qwen2.5-72B-Instruct', 'mistralai/Mistral-Small-24B-Instruct'],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    icon: 'waves',
    tint: '#4D6BFE',
    tier: 'freemium',
    blurb: 'DeepSeek Chat & Reasoner dengan harga masuk akal.',
    keyHint: 'sk-…',
    placeholder: 'sk-deepseek-…',
    envPrefix: 'DEEPSEEK_API_KEY',
    docs: 'platform.deepseek.com/api-keys',
    models: ['deepseek-chat', 'deepseek-reasoner'],
  },
];

export function providerById(id: string): ProviderDef | undefined {
  return PROVIDERS.find((p) => p.id === id);
}

export const CONNECTOR_CATALOG: {
  slug: string;
  name: string;
  icon: string;
  tint: string;
  scopes: string[];
  account: string;
  blurb: string;
}[] = [
  {
    slug: 'google',
    name: 'Google',
    icon: 'google',
    tint: '#EA4335',
    scopes: ['openid', 'email', 'drive.readonly'],
    account: 'dev@filosofi.app',
    blurb: 'OAuth 2.0 · Drive, Docs, Gemini workspace',
  },
  {
    slug: 'github',
    name: 'GitHub',
    icon: 'github',
    tint: '#E6EDF3',
    scopes: ['repo', 'read:org', 'workflow'],
    account: '@filosofi-dev',
    blurb: 'OAuth App · repo, actions, issue',
  },
  {
    slug: 'vercel',
    name: 'Vercel',
    icon: 'triangle',
    tint: '#9AA7BD',
    scopes: ['deployments:write', 'projects:read'],
    account: 'arcada-teams',
    blurb: 'Deploy preview & rollback dari chat',
  },
  {
    slug: 'huggingface',
    name: 'Hugging Face',
    icon: 'emoticon-happy-outline',
    tint: '#FFD21E',
    scopes: ['inference-api', 'models:read'],
    account: 'filosofi-bot',
    blurb: 'Pull model card & jalankan inference',
  },
  {
    slug: 'n8n',
    name: 'n8n',
    icon: 'gesture-tap-button',
    tint: '#EA4B71',
    scopes: ['execute:workflow', 'credentials:read'],
    account: 'n8n.selfhost',
    blurb: 'Trigger workflow otomatis hasil orchestrator',
  },
  {
    slug: 'slack',
    name: 'Slack',
    icon: 'slack',
    tint: '#3F9BFC',
    scopes: ['chat:write', 'channels:read'],
    account: '#agent-ops',
    blurb: 'Notifikasi run agent & approve step',
  },
  {
    slug: 'docker',
    name: 'Docker Hub',
    icon: 'docker',
    tint: '#2496ED',
    scopes: ['registry:pull', 'registry:push'],
    account: 'filosofi',
    blurb: 'Registry untuk image sandbox Alpine/Microbox',
  },
  {
    slug: 'notion',
    name: 'Notion',
    icon: 'note-text',
    tint: '#C9C9C4',
    scopes: ['read_content', 'insert_content'],
    account: 'workspace-ops',
    blurb: 'Tulis ringkasan run ke database notes',
  },
];

export const SKILL_LIBRARY = [
  'code-review',
  'refactor',
  'test-generation',
  'docs-writer',
  'security-audit',
  'perf-profiling',
  'db-migrate',
  'ui-polish',
  'release-cut',
  'log-triage',
];

export const LIBRARY_FILES = [
  'src/lib/router.ts',
  'src/lib/store.ts',
  'src/screens/ChatScreen.tsx',
  'src/agents/swarm.ts',
  'docker-compose.yml',
  'Dockerfile',
  '.github/workflows/ci.yml',
  'package.json',
  'README.md',
];
