import React, { useMemo, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen';
import { BackHeader } from '../components/BackHeader';
import { Chip, Empty, PrimaryButton } from '../components/ui';
import { useApp } from '../lib/AppContext';
import { colors } from '../lib/theme';
import { hashSeed } from '../lib/id';
import { RootStackParamList } from '../lib/navigation';
import { GeneratedAsset } from '../lib/types';
import { pollinationsImageUrl } from '../lib/infer';
import { pollinationsVideo, shareExport } from '../lib/export';
import { Image } from 'expo-image';

function Canvas({ asset, large }: { asset: GeneratedAsset; large?: boolean }) {
  const h = large ? 220 : 140;
  if (asset.imageUrl) {
    return (
      <Image source={{ uri: asset.imageUrl }} style={{ width: '100%', height: h, backgroundColor: '#071018' }} contentFit="cover" />
    );
  }
  return (
    <View style={[styles.canvas, { height: h }]}>
      <Text style={styles.stampTxt}>NO IMAGE URL</Text>
    </View>
  );
}

export function StudioScreen() {
  const app = useApp();
  const nav = useNavigation<NativeStackNavigationProp<RootStackParamList>>();
  const [prompt, setPrompt] = useState('Poster MusGo-OS sovereign AI, neon terminal, gotong-royong');
  const [busy, setBusy] = useState(false);
  const [kind, setKind] = useState<'image' | 'video' | 'document' | 'text'>('image');

  const generate = async () => {
    const p = prompt.trim();
    if (!p) return;
    setBusy(true);
    const seed = hashSeed(p + String(Date.now()));
    const title = p.replace(/[^a-zA-Z0-9\s]/g, ' ').trim().split(/\s+/).slice(0, 5).join('-').toLowerCase() || 'canvas';
    if (kind === 'image') {
      const imageUrl = pollinationsImageUrl(p);
      const asset = app.addAsset({ prompt: p, seed, palette: ['#3dff9a', '#5ec8ff'], title, imageUrl, kind: 'image', downloadUrl: imageUrl });
      setBusy(false);
      nav.navigate('AssetDetail', { id: asset.id });
      return;
    }
    if (kind === 'video') {
      const downloadUrl = pollinationsVideo(p);
      const asset = app.addAsset({ prompt: p, seed, palette: ['#5ec8ff', '#c4b5fd'], title, imageUrl: downloadUrl, kind: 'video', downloadUrl });
      setBusy(false);
      nav.navigate('AssetDetail', { id: asset.id });
      return;
    }
    const body =
      kind === 'document'
        ? `# ${title}\n\n${p}\n\n---\nGenerated by Human CLI · ${new Date().toISOString()}\n`
        : p;
    const asset = app.addAsset({ prompt: p, seed, palette: ['#f0c14b'], title, kind, body, downloadUrl: '' });
    app.addSandbox({ path: `/exports/${title}.${kind === 'document' ? 'md' : 'txt'}`, content: body, mime: kind === 'document' ? 'text/markdown' : 'text/plain' });
    setBusy(false);
    nav.navigate('AssetDetail', { id: asset.id });
  };

  return (
    <Screen>
      <BackHeader title="Multimodal" subtitle="text · dokumen · image · video" />
      <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 6, paddingHorizontal: 16, paddingBottom: 8 }}>
        {(['text', 'document', 'image', 'video'] as const).map((k) => (
          <Chip key={k} label={k.toUpperCase()} active={kind === k} onPress={() => setKind(k)} />
        ))}
      </View>
      <View style={styles.box}>
        <TextInput
          value={prompt}
          onChangeText={setPrompt}
          placeholder="Deskripsikan gambar…"
          placeholderTextColor={colors.textDim}
          multiline
          style={styles.input}
        />
        <PrimaryButton title={busy ? 'Meminta…' : 'Generate (Pollinations)'} icon="color-wand-outline" onPress={generate} disabled={busy} />
      </View>
      <FlatList
        data={app.assets}
        keyExtractor={(it) => it.id}
        numColumns={2}
        columnWrapperStyle={{ gap: 10 }}
        contentContainerStyle={{ padding: 16, paddingBottom: 40, gap: 10 }}
        ListEmptyComponent={<Empty icon="images-outline" title="Gallery kosong" body="Generate lewat Pollinations. URL gambar nyata tersimpan." />}
        renderItem={({ item }) => (
          <Pressable style={styles.card} onPress={() => nav.navigate('AssetDetail', { id: item.id })}>
            <Canvas asset={item} />
            <Text style={styles.cardTitle} numberOfLines={1}>{item.title}</Text>
            <Text style={styles.cardSub} numberOfLines={2}>{item.prompt}</Text>
          </Pressable>
        )}
      />
    </Screen>
  );
}

export function AssetDetailScreen({ route, navigation }: { route: { params: { id: string } }; navigation: { goBack: () => void } }) {
  const app = useApp();
  const asset = useMemo(() => app.assets.find((a) => a.id === route.params.id), [app.assets, route.params.id]);
  if (!asset) {
    return (
      <Screen>
        <Empty icon="alert-circle-outline" title="Tidak ditemukan" body="Artefak sudah dihapus." />
      </Screen>
    );
  }
  const link = asset.downloadUrl || asset.imageUrl || '';
  return (
    <Screen>
      <BackHeader title={asset.title} subtitle={asset.kind || 'image'} />
      <View style={{ paddingHorizontal: 16 }}>
        {asset.imageUrl ? <Canvas asset={asset} large /> : null}
        <Text style={styles.prompt}>{asset.prompt}</Text>
        {asset.body ? <Text style={styles.dl} selectable>{asset.body}</Text> : null}
        {link ? <Text style={styles.dl} selectable>Download: {link}</Text> : null}
        <PrimaryButton title="Export .md" icon="download-outline" onPress={() => shareExport('md', asset.title, asset.prompt, asset.body || link)} />
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  head: { paddingHorizontal: 16, paddingBottom: 10, flexDirection: 'row', alignItems: 'center' },
  title: { color: colors.text, fontSize: 20, fontWeight: '800' },
  sub: { color: colors.textDim, fontSize: 12, marginTop: 2 },
  box: { paddingHorizontal: 16, paddingBottom: 8 },
  input: {
    backgroundColor: colors.bgInput, borderWidth: 1, borderColor: colors.border,
    borderRadius: 14, color: colors.text, minHeight: 80, padding: 12, marginBottom: 10,
    textAlignVertical: 'top',
  },
  card: {
    flex: 1, backgroundColor: colors.bgCard, borderRadius: 14, borderWidth: 1,
    borderColor: colors.border, overflow: 'hidden', paddingBottom: 10,
  },
  canvas: {
    backgroundColor: '#071018', overflow: 'hidden', position: 'relative',
  },
  blob: { position: 'absolute', borderRadius: 80, opacity: 0.85 },
  stamp: { position: 'absolute', left: 10, bottom: 10 },
  stampTxt: { color: colors.green, fontSize: 10, fontWeight: '900', letterSpacing: 2 },
  stampSeed: { color: colors.textDim, fontSize: 10 },
  cardTitle: { color: colors.text, fontWeight: '700', fontSize: 12, marginTop: 8, paddingHorizontal: 10 },
  cardSub: { color: colors.textDim, fontSize: 11, marginTop: 3, paddingHorizontal: 10 },
  prompt: { color: colors.text, fontSize: 14, marginTop: 14, lineHeight: 20 },
  pals: { flexDirection: 'row', gap: 8, marginTop: 12 },
  pal: { width: 28, height: 28, borderRadius: 8, borderWidth: 1, borderColor: colors.border },
  dl: { color: colors.textMuted, fontSize: 12, marginTop: 14, lineHeight: 18 },
});
